/* ===========================================================
   Reference geography data for the "browse list" curtain menu
   and for the country-level province/region maps.

   - `countries` is a near-complete list of the world's countries.
   - `provinces` is each country's first-level regions/states/provinces.
   - `cities` is a short list of well-known cities for that COUNTRY
     as a whole (capital + the biggest/most visited ones). It is not
     mapped to a specific province.
   - `map` is the filename (without .svg) of that country's province-
     level map in /maps, when one is available. The map's own region
     names are used as `provinces` so the curtain and the map always
     agree — except Italy, which keeps Italian names for the curtain
     (script.js carries a small alias table to match them to the map).

   Pakistan is intentionally left without a map: the only available
   dataset for it is 144 districts, too granular for this level.

   Coverage is intentionally uneven: most of Europe and the larger,
   most-visited countries worldwide have real lists. Many smaller or
   less-traveled countries are left empty — typing a custom name
   always works regardless, for anything missing here.
   =========================================================== */

const GEO_DATA = {
  countries: [
    { name: "Afghanistan", provinces: [] },
    { name: "Albania", provinces: [], cities: ["Tirana", "Sarandë", "Berat", "Shkodër", "Vlorë"] },
    { name: "Algeria", provinces: [] },
    { name: "Andorra", provinces: [] },
    { name: "Angola", provinces: [] },
    { name: "Antigua and Barbuda", provinces: [] },
    { name: "Argentina", provinces: ["Buenos Aires Province", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago del Estero", "Tierra del Fuego", "Tucumán", "Ciudad Autónoma de Buenos Aires"], cities: ["Buenos Aires", "Mendoza", "Bariloche", "Ushuaia", "Córdoba", "Salta"] },
    { name: "Armenia", provinces: [] },
    { name: "Australia", provinces: ["Australian Capital Territory", "New South Wales", "Northern Territory Groote Eylandt", "Northern Territory Mainland", "Northern Territory Melville Island", "Queensland Fraser Island", "Queensland Mainland", "Queensland Mornington Island", "South Australia Kangaroo Island", "South Australia Mainland", "Tasmania Cape Barren", "Tasmania Flinders Island", "Tasmania King Currie Island", "Tasmania Mainland", "Victoria", "Western Australia"], cities: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Cairns", "Gold Coast", "Hobart"], map: "australia" },
    { name: "Austria", provinces: ["Burgenland", "Carinthia", "Lower Austria", "Salzburg", "Styria", "Tyrol", "Upper Austria", "Vienna", "Vorarlberg"], cities: ["Vienna", "Salzburg", "Innsbruck", "Graz", "Linz", "Hallstatt"], map: "austria" },
    { name: "Azerbaijan", provinces: [] },
    { name: "Bahamas", provinces: [] },
    { name: "Bahrain", provinces: [] },
    { name: "Bangladesh", provinces: [] },
    { name: "Barbados", provinces: [] },
    { name: "Belarus", provinces: [] },
    { name: "Belgium", provinces: ["Flanders", "Wallonia", "Brussels-Capital Region"], cities: ["Brussels", "Antwerp", "Bruges", "Ghent", "Liège"] },
    { name: "Belize", provinces: [] },
    { name: "Benin", provinces: [] },
    { name: "Bhutan", provinces: [] },
    { name: "Bolivia", provinces: [], cities: ["La Paz", "Sucre", "Uyuni", "Santa Cruz de la Sierra"] },
    { name: "Bosnia and Herzegovina", provinces: [], cities: ["Sarajevo", "Mostar", "Banja Luka"] },
    { name: "Botswana", provinces: [] },
    { name: "Brazil", provinces: ["Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Pará", "Paraíba", "Paraná", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "São Paulo", "Sergipe", "Tocantins"], cities: ["Rio de Janeiro", "São Paulo", "Salvador", "Brasília", "Florianópolis"], map: "brazil" },
    { name: "Brunei", provinces: [] },
    { name: "Bulgaria", provinces: [], cities: ["Sofia", "Plovdiv", "Varna", "Bansko"] },
    { name: "Burkina Faso", provinces: [] },
    { name: "Burundi", provinces: [] },
    { name: "Cabo Verde", provinces: ["Brava", "Boa Vista", "Santa Catarina", "Santa Catarina do Fogo", "Santa Cruz", "Maio", "Mosteiros", "Paul", "Porto Novo", "Praia", "Ribeira Brava", "Ribeira Grande", "Ribeira Grande de Santiago", "São Domingos", "São Filipe", "Sal", "São Miguel", "São Lourenço dos Órgãos", "São Salvador do Mundo", "São Vicente", "Tarrafal", "Tarrafal de São Nicolau"], map: "cape-verde" },
    { name: "Cambodia", provinces: ["Banteay Meanchey", "Battambang", "Tboung Khmum", "Kampong Cham", "Kampong Chhnang", "Kampong Speu", "Kampong Thom", "Kampot", "Kandal", "Koh Kong", "Kratie", "Mondulkiri", "Phnom Penh", "Preah Vihear", "Prey Veng", "Pursat", "Rattanakkiri", "Siem Reap", "Preah Sihanouk", "Stung Treng", "Svay Rieng", "Ta Keo", "Oddar Meanchey", "Kep", "Pailin"], cities: ["Phnom Penh", "Siem Reap", "Sihanoukville"], map: "cambodia" },
    { name: "Cameroon", provinces: ["Adamawa", "Central", "East", "Far North", "Littoral", "North", "Northwest", "South", "Southwest", "West"], map: "cameroon" },
    { name: "Canada", provinces: ["Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia", "Nunavut", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Yukon"], cities: ["Toronto", "Vancouver", "Montreal", "Quebec City", "Ottawa", "Calgary", "Banff"], map: "canada" },
    { name: "Central African Republic", provinces: [] },
    { name: "Chad", provinces: [] },
    { name: "Chile", provinces: [], cities: ["Santiago", "Valparaíso", "San Pedro de Atacama", "Punta Arenas"] },
    { name: "China", provinces: ["Anhui", "Beijing", "Chongqing", "Fujian", "Gansu", "Guangdong", "Guangxi Zhuang", "Guizhou", "Hainan", "Hebei", "Heilongjiang", "Henan", "Hong Kong", "Hubei", "Hunan", "Jiangsu", "Jiangxi", "Jilin", "Liaoning", "Macau", "Nei Mongol", "Ningxia Hui", "Quinghai", "Shaanxi", "Shandong", "Shanghai", "Shanxi", "Sichuan", "Tianjin", "Xinjiang Uygur", "Xizang (Tibet) ", "Yunnan", "Zhejiang"], cities: ["Beijing", "Shanghai", "Hong Kong", "Xi'an", "Guangzhou", "Chengdu", "Shenzhen"], map: "china" },
    { name: "Colombia", provinces: ["Amazonas", "Antioquia", "Arauca", "Atlántico", "Bogotá", "Bolívar", "Boyacá", "Caldas", "Caquetá", "Casanare", "Cauca", "Cesar", "Chocó", "Córdoba", "Cundinamarca", "Guainía", "Guaviar", "Huila", "La Guajira", "Magdalena", "Meta", "Nariño", "North Santander", "Putumayo", "Quindío", "Risaralda", "San Andrés y Providencia", "Santander", "Sucre", "Tolima", "Valle del Cauca", "Vichada", "Vaupés"], cities: ["Bogotá", "Medellín", "Cartagena", "Cali"], map: "colombia" },
    { name: "Comoros", provinces: [] },
    { name: "Congo (Republic of the)", provinces: [] },
    { name: "Congo (Democratic Republic of the)", provinces: [] },
    { name: "Costa Rica", provinces: [], cities: ["San José", "Tamarindo", "Manuel Antonio", "Monteverde"] },
    { name: "Croatia", provinces: ["Zagreb County", "Krapina-Zagorje", "Sisak-Moslavina", "Karlovac", "Varaždin", "Koprivnica-Križevci", "Bjelovar-Bilogora", "Primorje-Gorski Kotar", "Lika-Senj", "Virovitica-Podravina", "Požega-Slavonia", "Brod-Posavina", "Zadar", "Osijek-Baranja", "Šibenik-Knin", "Vukovar-Syrmia", "Split-Dalmatia", "Istria", "Dubrovnik-Neretva", "Međimurje", "City of Zagreb"], cities: ["Zagreb", "Split", "Dubrovnik", "Zadar", "Rovinj", "Pula"] },
    { name: "Cuba", provinces: [], cities: ["Havana", "Varadero", "Trinidad", "Santiago de Cuba"] },
    { name: "Cyprus", provinces: [], cities: ["Nicosia", "Limassol", "Paphos", "Ayia Napa"] },
    { name: "Czechia", provinces: ["Prague", "Central Bohemian", "South Bohemian", "Plzeň", "Karlovy Vary", "Ústí nad Labem", "Liberec", "Hradec Králové", "Pardubice", "Olomouc", "Moravian-Silesian", "South Moravian", "Zlín", "Vysočina"], cities: ["Prague", "Brno", "Český Krumlov", "Karlovy Vary"] },
    { name: "Denmark", provinces: ["Hovedstaden", "Midtjylland", "Nordjylland", "Sjælland", "Syddanmark"], cities: ["Copenhagen", "Aarhus", "Odense", "Aalborg"], map: "denmark" },
    { name: "Djibouti", provinces: [] },
    { name: "Dominica", provinces: [] },
    { name: "Dominican Republic", provinces: [], cities: ["Santo Domingo", "Punta Cana", "Puerto Plata"] },
    { name: "Ecuador", provinces: [], cities: ["Quito", "Guayaquil", "Galápagos Islands", "Cuenca"] },
    { name: "Egypt", provinces: ["Cairo", "Giza", "Alexandria", "Luxor", "Aswan", "Red Sea", "South Sinai", "Matrouh"], cities: ["Cairo", "Luxor", "Aswan", "Sharm El Sheikh", "Hurghada", "Alexandria"] },
    { name: "El Salvador", provinces: [] },
    { name: "Equatorial Guinea", provinces: [] },
    { name: "Eritrea", provinces: [] },
    { name: "Estonia", provinces: [], cities: ["Tallinn", "Tartu"] },
    { name: "Eswatini", provinces: [] },
    { name: "Ethiopia", provinces: [] },
    { name: "Fiji", provinces: [] },
    { name: "Finland", provinces: ["Lapland", "North Ostrobothnia", "Kainuu", "North Karelia", "North Savo", "South Savo", "South Ostrobothnia", "Ostrobothnia", "Central Ostrobothnia", "Pirkanmaa", "Satakunta", "Central Finland", "Päijänne Tavastia", "Tavastia Proper", "South Karelia", "Kymenlaakso", "Uusimaa", "Southwest Finland", "Åland"], cities: ["Helsinki", "Tampere", "Turku", "Rovaniemi"] },
    { name: "France", provinces: ["Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté", "Bretagne", "Centre-Val de Loire", "Corse", "Grand Est", "Hauts-de-France", "Île-de-France", "Normandie", "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire", "Provence-Alpes-Côte d'Azur"], cities: ["Paris", "Lyon", "Marseille", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille", "Rennes", "Annecy"], map: "france" },
    { name: "Gabon", provinces: [] },
    { name: "Gambia", provinces: [] },
    { name: "Georgia", provinces: [], cities: ["Tbilisi", "Batumi", "Kazbegi"] },
    { name: "Germany", provinces: ["Baden-Wurttemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse", "Lower Saxony", "Mecklenburg-Vorpommern", "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland", "Saxony", "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia"], cities: ["Berlin", "Munich", "Hamburg", "Cologne", "Frankfurt", "Stuttgart", "Düsseldorf", "Dresden", "Leipzig", "Nuremberg"], map: "germany" },
    { name: "Ghana", provinces: [] },
    { name: "Greece", provinces: ["Attica", "Central Greece", "Central Macedonia", "Crete", "East Macedonia and Thrace", "Epirus", "Ionian Islands", "Mount Athos", "North Aegean", "Peloponnese", "South Aegean", "Thessaly", "West Greece", "West Macedonia"], cities: ["Athens", "Thessaloniki", "Heraklion", "Santorini", "Mykonos", "Rhodes"], map: "greece" },
    { name: "Grenada", provinces: [] },
    { name: "Guatemala", provinces: [], cities: ["Guatemala City", "Antigua Guatemala", "Lake Atitlán"] },
    { name: "Guinea", provinces: [] },
    { name: "Guinea-Bissau", provinces: [] },
    { name: "Guyana", provinces: [] },
    { name: "Haiti", provinces: [] },
    { name: "Honduras", provinces: ["Atlántida", "Choluteca", "Colón", "Comayagua", "Copán", "Cortés", "El Paraíso", "Francisco Morazán", "Gracias a Dios", "Intibucá", "Islas de la Bahía", "La Paz", "Lempira", "Ocotepeque", "Olancho", "Santa Bárbara", "Valle", "Yoro"], map: "honduras" },
    { name: "Hungary", provinces: ["Bács-Kiskun", "Baranya", "Békés", "Borsod-Abaúj-Zemplén", "Csongrád-Csanád", "Fejér", "Győr-Moson-Sopron", "Hajdú-Bihar", "Heves", "Jász-Nagykun-Szolnok", "Komárom-Esztergom", "Nógrád", "Pest", "Somogy", "Szabolcs-Szatmár-Bereg", "Tolna", "Vas", "Veszprém", "Zala", "Budapest"], cities: ["Budapest", "Debrecen", "Szeged", "Pécs"] },
    { name: "Iceland", provinces: ["Capital Region", "Southern Peninsula", "Western Region", "Westfjords", "Northwestern Region", "Northeastern Region", "Eastern Region", "Southern Region"], cities: ["Reykjavik", "Akureyri"] },
    { name: "India", provinces: ["Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Dadra and Nagar Haveli", "Daman and Diu", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Lakshadweep", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", "Nagaland", "Odisha", "Puducherry", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"], cities: ["Delhi", "Mumbai", "Jaipur", "Goa", "Agra", "Varanasi", "Bangalore"], map: "india" },
    { name: "Indonesia", provinces: ["Aceh", "Bali", "Bangka Belitung", "Bengkulu", "Banten", "Gorontalo", "Jambi", "Jawa Barat", "Jawa Timur", "Jakarta Raya", "Jawa Tengah", "Kalimantan Barat", "Kalimantan Timur", "Kepulauan Riau", "Kalimantan Selatan", "Kalimantan Tengah", "Kalimantan Utara", "Lampung", "Maluku", "Maluku Utara", "Nusa Tenggara Barat", "Nusa Tenggara Timur", "Papua", "Papua Barat", "Riau", "Sulawesi Utara", "Sumatera Barat", "Sulawesi Tenggara", "Sulawesi Selatan", "Sulawesi Barat", "Sumatera Selatan", "Sulawesi Tengah", "Sumatera Utara", "Yogyakarta"], cities: ["Jakarta", "Denpasar (Bali)", "Yogyakarta", "Bandung", "Surabaya"], map: "indonesia" },
    { name: "Iran", provinces: [] },
    { name: "Iraq", provinces: [] },
    { name: "Ireland", provinces: ["Carlow", "Cavan", "Clare", "Cork", "Donegal", "Dublin", "Galway", "Kerry", "Kildare", "Kilkenny", "Laois", "Leitrim", "Limerick", "Longford", "Louth", "Mayo", "Meath", "Monaghan", "Offaly", "Roscommon", "Sligo", "Tipperary", "Waterford", "Westmeath", "Wexford", "Wicklow"], cities: ["Dublin", "Cork", "Galway", "Limerick", "Killarney"] },
    { name: "Israel", provinces: ["Golan Heights", "Hadarom", "Hamerkaz", "Hazafon", "Hefa", "Jerusalem", "Palestine", "Tel Aviv"], cities: ["Jerusalem", "Tel Aviv", "Haifa", "Eilat"], map: "israel" },
    {
      name: "Italy",
      provinces: [
        "Piemonte", "Valle d'Aosta", "Liguria", "Lombardia", "Trentino-Alto Adige", "Veneto", "Friuli-Venezia Giulia", "Emilia-Romagna", "Toscana", "Umbria", "Marche", "Lazio", "Abruzzo", "Molise", "Campania", "Puglia", "Basilicata", "Calabria", "Sicilia", "Sardegna"
      ],
      cities: ["Roma", "Milano", "Napoli", "Torino", "Palermo", "Genova", "Bologna", "Firenze", "Bari", "Catania", "Venezia", "Verona", "Trento", "Bolzano", "Canazei", "Merano", "Cortina d'Ampezzo"],
      map: "italy"
    },
    { name: "Ivory Coast", provinces: [] },
    { name: "Jamaica", provinces: [] },
    { name: "Japan", provinces: ["Aichi", "Akita", "Aomori", "Chiba", "Ehime", "Fukui", "Fukuoka", "Fukushima", "Gifu", "Gunma", "Hiroshima", "Hokkaido", "Hyogo", "Ibaraki", "Ishikawa", "Iwate", "Kagawa", "Kagoshima", "Kanagawa", "Kochi", "Kumamoto", "Kyoto", "Mie", "Miyagi", "Miyazaki", "Nagano", "Nagasaki", "Nara", "Niigata", "Oita", "Okayama", "Okinawa", "Osaka", "Saga", "Saitama", "Shiga", "Shimane", "Shizuoka", "Tochigi", "Tokushima", "Tokyo", "Tottori", "Toyama", "Wakayama", "Yamagata", "Yamaguchi", "Yamanashi"], cities: ["Tokyo", "Osaka", "Kyoto", "Hiroshima", "Sapporo", "Nagoya", "Yokohama", "Nara"], map: "japan" },
    { name: "Jordan", provinces: [], cities: ["Amman", "Petra", "Wadi Rum", "Aqaba"] },
    { name: "Kazakhstan", provinces: [] },
    { name: "Kenya", provinces: ["Baringo", "Bomet", "Bungoma", "Busia", "Embu", "Garissa", "Homa Bay", "Isiolo", "Kajiado", "Kakamega", "Keiyo-Marakwet", "Kericho", "Kiambu", "Kilifi", "Kirinyaga", "Kisii", "Kisumu", "Kitui", "Kwale", "Laikipia", "Lamu", "Machakos", "Makueni", "Mandera", "Marsabit", "Meru", "Mombasa", "Migori", "Murang'a", "Nairobi", "Nakuru", "Narok", "Nandi", "Nyamira", "Nyandarua", "Nyeri", "Samburu", "Siaya", "Tana River", "Taita Taveta", "Tharaka", "Trans Nzoia", "Turkana", "Uasin Gishu", "Vihiga", "Wajir", "West Pokot"], cities: ["Nairobi", "Mombasa", "Maasai Mara"], map: "kenya" },
    { name: "Kiribati", provinces: [] },
    { name: "Kosovo", provinces: [], cities: ["Pristina", "Prizren"] },
    { name: "Kuwait", provinces: [] },
    { name: "Kyrgyzstan", provinces: [] },
    { name: "Laos", provinces: [], cities: ["Vientiane", "Luang Prabang"] },
    { name: "Latvia", provinces: [], cities: ["Riga"] },
    { name: "Lebanon", provinces: [], cities: ["Beirut", "Byblos"] },
    { name: "Lesotho", provinces: [] },
    { name: "Liberia", provinces: [] },
    { name: "Libya", provinces: [] },
    { name: "Liechtenstein", provinces: [], cities: ["Vaduz"] },
    { name: "Lithuania", provinces: [], cities: ["Vilnius", "Kaunas"] },
    { name: "Luxembourg", provinces: [], cities: ["Luxembourg City"] },
    { name: "Madagascar", provinces: [] },
    { name: "Malawi", provinces: [] },
    { name: "Malaysia", provinces: [], cities: ["Kuala Lumpur", "Penang", "Langkawi", "Malacca"] },
    { name: "Maldives", provinces: [], cities: ["Malé"] },
    { name: "Mali", provinces: [] },
    { name: "Malta", provinces: [], cities: ["Valletta", "Sliema", "Mdina"] },
    { name: "Marshall Islands", provinces: [] },
    { name: "Mauritania", provinces: [] },
    { name: "Mauritius", provinces: [], cities: ["Port Louis"] },
    { name: "Mexico", provinces: ["Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "Chiapas", "Chihuahua", "Coahuila", "Colima", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "Mexico City", "México", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas"], cities: ["Mexico City", "Cancún", "Guadalajara", "Playa del Carmen", "Tulum", "Oaxaca City"], map: "mexico" },
    { name: "Micronesia", provinces: [] },
    { name: "Moldova", provinces: ["Anenii Noi", "Bălţi", "Bender", "Briceni", "Basarabeasca", "Cahul", "Călăraşi", "Cimişlia", "Criuleni", "Căuşeni", "Cantemir", "Chişinău", "Donduşeni", "Drochia", "Dubăsari", "Edineţ", "Făleşti", "Floreşti", "Unitatea Teritorială Autonomă Găgăuzia (UTAG)", "Glodeni", "Hînceşti", "Ialoveni", "Leova", "Nisporeni", "Ocniţa", "Orhei", "Rezina", "Rîşcani", "Şoldăneşti", "Sîngerei", "Unitatea Teritorială din Stînga Nistrului (Transnistria)", "Soroca", "Străşeni", " Ştefan Vodă", "Taraclia", "Teleneşti", "Ungheni"], map: "moldova" },
    { name: "Monaco", provinces: [], cities: ["Monte Carlo"] },
    { name: "Mongolia", provinces: [], cities: ["Ulaanbaatar"] },
    { name: "Montenegro", provinces: [], cities: ["Kotor", "Budva", "Podgorica"] },
    { name: "Morocco", provinces: ["Tanger-Tétouan-Al Hoceïma", "Oriental", "Fès-Meknès", "Rabat-Salé-Kénitra", "Béni Mellal-Khénifra", "Casablanca-Settat", "Marrakech-Safi", "Drâa-Tafilalet", "Souss-Massa", "Guelmim-Oued Noun", "Laâyoune-Sakia El Hamra", "Dakhla-Oued Ed-Dahab"], cities: ["Marrakech", "Casablanca", "Fes", "Rabat", "Chefchaouen", "Essaouira"] },
    { name: "Mozambique", provinces: [] },
    { name: "Myanmar", provinces: [] },
    { name: "Namibia", provinces: [] },
    { name: "Nauru", provinces: [] },
    { name: "Nepal", provinces: [], cities: ["Kathmandu", "Pokhara"] },
    { name: "Netherlands", provinces: ["Drenthe", "Flevoland", "Friesland", "Gelderland", "Groningen", "Limburg", "Noord-Brabant", "Noord-Holland", "Overijssel", "Utrecht", "Zeeland", "Zuid-Holland"], cities: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"], map: "netherlands" },
    { name: "New Zealand", provinces: ["Auckland", "Bay of Plenty", "Canterbury", "Chatham Islands Territory", "Gisborne District", "Hawke's Bay", "Manawatu-Wanganui", "Marlborough District", "Nelson City", "Northland", "Otago", "Southland", "Taranaki", "Tasman District", "Waikato", "Wellington", "West Coast"], cities: ["Auckland", "Wellington", "Queenstown", "Christchurch", "Rotorua"], map: "new-zealand" },
    { name: "Nicaragua", provinces: [] },
    { name: "Niger", provinces: [] },
    { name: "Nigeria", provinces: ["Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Benue", "Borno", "Bayelsa", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu", "Federal Capital Territory", "Gombe", "Imo", "Jigawa", "Kaduna", "Kebbi", "Kano", "Kogi", "Katsina", "Kwara", "Lagos", "Nassarawa", "Niger", "Ogun", "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe", "Zamfara"], map: "nigeria" },
    { name: "North Korea", provinces: [] },
    { name: "North Macedonia", provinces: [], cities: ["Skopje", "Ohrid"] },
    { name: "Norway", provinces: ["Oslo", "Rogaland", "Møre og Romsdal", "Nordland", "Østfold", "Akershus", "Buskerud", "Innlandet", "Vestfold", "Telemark", "Agder", "Vestland", "Trøndelag", "Troms", "Finnmark"], cities: ["Oslo", "Bergen", "Trondheim", "Tromsø"] },
    { name: "Oman", provinces: [] },
    { name: "Pakistan", provinces: [] },
    { name: "Palau", provinces: [] },
    { name: "Palestine", provinces: [] },
    { name: "Panama", provinces: [], cities: ["Panama City", "Bocas del Toro"] },
    { name: "Papua New Guinea", provinces: [] },
    { name: "Paraguay", provinces: [] },
    { name: "Peru", provinces: [], cities: ["Lima", "Cusco", "Machu Picchu (Aguas Calientes)", "Arequipa"] },
    { name: "Philippines", provinces: ["National Capital Region (Manila)", "Cebu (Central Visayas)", "Davao Region", "Palawan (Mimaropa)", "Ilocos Region", "Bicol Region"], cities: ["Manila", "Cebu City", "Davao", "Boracay (Aklan)", "Palawan"] },
    { name: "Poland", provinces: ["Greater Poland", "Kuyavian-Pomeranian", "Lesser Poland", "Łódź", "Lower Silesian", "Lublin", "Lubusz", "Masovian", "Opole", "Podlaskie", "Pomeranian", "Silesian", "Subcarpathian", "Świętokrzyskie", "Warmian-Masurian", "West Pomeranian"], cities: ["Warsaw", "Kraków", "Gdańsk", "Wrocław", "Poznań"] },
    { name: "Portugal", provinces: ["Aveiro", "Beja", "Braga", "Bragança", "Castelo Branco", "Coimbra", "Évora", "Faro", "Guarda", "Leiria", "Lisboa", "Portalegre", "Porto", "Santarém", "Setúbal", "Viana do Castelo", "Vila Real", "Viseu", "Açores", "Madeira"], cities: ["Lisbon", "Porto", "Faro", "Coimbra", "Braga", "Sintra"] },
    { name: "Qatar", provinces: [], cities: ["Doha"] },
    { name: "Romania", provinces: ["Alba", "Argeș", "Arad", "Bacău", "Bihor", "Bistrița-Năsăud", "Brăila", "Botoșani", "Bucharest", "Brașov", "Buzău", "Cluj", "Călărași", "Caraș-Severin", "Constanța", "Covasna", "Dâmbovița", "Dolj", "Gorj", "Galați", "Giurgiu", "Hunedoara", "Harghita", "Ilfov", "Ialomița", "Iași", "Mehedinți", "Maramureș", "Mureș", "Neamț", "Olt", "Prahova", "Sibiu", "Sălaj", "Satu Mare", "Suceava", "Tulcea", "Timiș", "Teleorman", "Vâlcea", "Vrancea", "Vaslui"], cities: ["Bucharest", "Brașov", "Sibiu", "Cluj-Napoca"], map: "romania" },
    { name: "Russia", provinces: [], cities: ["Moscow", "Saint Petersburg"] },
    { name: "Rwanda", provinces: [] },
    { name: "Saint Kitts and Nevis", provinces: [] },
    { name: "Saint Lucia", provinces: [] },
    { name: "Saint Vincent and the Grenadines", provinces: [] },
    { name: "Samoa", provinces: [] },
    { name: "San Marino", provinces: [], cities: ["City of San Marino"] },
    { name: "Sao Tome and Principe", provinces: [] },
    { name: "Saudi Arabia", provinces: ["Ryiadh", "Mecca", "Medina", "Eastern Province", "Al-Qassim", "Ha'il", "Tabuk", "Northern Borders", "Jizan", "Najran", "Al-Bahah", "Al-Jawf", "Asir"], cities: ["Riyadh", "Jeddah", "Mecca", "AlUla"], map: "saudi-arabia" },
    { name: "Senegal", provinces: [] },
    { name: "Serbia", provinces: [], cities: ["Belgrade", "Novi Sad"] },
    { name: "Seychelles", provinces: [] },
    { name: "Sierra Leone", provinces: [] },
    { name: "Singapore", provinces: [], cities: ["Singapore"] },
    { name: "Slovakia", provinces: [], cities: ["Bratislava", "Košice"] },
    { name: "Slovenia", provinces: ["Gorenjska", "Goriška", "Jugovzhodna Slovenija", "Koroška", "Notranjsko-kraška", "Obalno-kraška", "Osrednjeslovenska", "Podravska", "Pomurska", "Posavska", "Savinjska", "Zasavska"], cities: ["Ljubljana", "Bled", "Piran"] },
    { name: "Solomon Islands", provinces: [] },
    { name: "Somalia", provinces: [] },
    { name: "South Africa", provinces: ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Mpumalanga", "North West", "Northern Cape", "Western Cape"], cities: ["Cape Town", "Johannesburg", "Durban", "Pretoria"] },
    { name: "South Korea", provinces: ["Busan", "Daegu", "Daejeon", "Gangwon", "Gwangju", "Gyeonggi", "Incheon", "Jeju", "North Chungcheong", "North Gyeongsang", "North Jeolla", "Sejong", "Seoul", "South Chungcheong", "South Gyeongsang", "South Jeolla", "Ulsan"], cities: ["Seoul", "Busan", "Jeju", "Incheon", "Gyeongju"], map: "south-korea" },
    { name: "South Sudan", provinces: [] },
    { name: "Spain", provinces: ["Andalusia", "Aragon", "Asturias", "Balearic Islands", "Basque Country", "Canary Islands", "Cantabria", "Castile and Leon", "Castile-La Mancha", "Catalonia", "Extremadura", "Galicia", "La Rioja", "Madrid", "Murcia", "Navarre", "Valencia"], cities: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Bilbao", "Málaga", "Zaragoza", "Granada", "San Sebastián", "Palma de Mallorca"], map: "spain" },
    { name: "Sri Lanka", provinces: ["Colombo", "Gampaha", "Kalutara", "Kandy", "Matale", "Nuwara Eliya", "Galle", "Matara", "Hambantota", "Jaffna", "Kilinochchi", "Mannar", "Vavuniya", "Mullaitivu", "Batticaloa", "Ampara", "Trincomalee", "Kurunegala", "Puttalam", "Anuradhapura", "Polonnaruwa", "Badulla", "Moneragala", "Ratnapura", "Kegalle"], cities: ["Colombo", "Kandy", "Galle", "Ella"], map: "sri-lanka" },
    { name: "Sudan", provinces: [] },
    { name: "Suriname", provinces: [] },
    { name: "Sweden", provinces: ["Blekinge", "Dalarna", "Gävleborg", "Gotland", "Halland", "Jämtland", "Jönköping", "Kalmar", "Kronoberg", "Norrbotten", "Örebro", "Östergötland", "Skåne", "Södermanland", "Stockholm", "Uppsala", "Värmland", "Västerbotten", "Västernorrland", "Västmanland", "Västra Götaland"], cities: ["Stockholm", "Gothenburg", "Malmö", "Uppsala"], map: "sweden" },
    { name: "Switzerland", provinces: ["Zürich", "Bern", "Luzern", "Uri", "Schwyz", "Obwalden", "Nidwalden", "Glarus", "Zug", "Fribourg", "Solothurn", "Basel-Stadt", "Basel-Landschaft", "Schaffhausen", "Appenzell Ausserrhoden", "Appenzell Innerrhoden", "St. Gallen", "Graubünden", "Aargau", "Thurgau", "Ticino", "Vaud", "Valais", "Neuchâtel", "Genève", "Jura"], cities: ["Zürich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne", "Lugano", "Interlaken", "Zermatt"] },
    { name: "Syria", provinces: [] },
    { name: "Taiwan", provinces: ["Changhua County", "Chiayi City", "Chiayi County", "Hualien County", "Hsinchu City", "Hsinchu County", "Kaohsiung City", "Keelung City", "Kinmen County", "Lienchiang County", "Miaoli County", "Nantou County", "New Taipei City", "Penghu County", "Pingtung County", "Taichung City", "Tainan City", "Taipei City", "Taitung County", "Taoyuan City", "Yilan County", "Yunlin County"], cities: ["Taipei", "Kaohsiung", "Taichung"], map: "taiwan" },
    { name: "Tajikistan", provinces: [] },
    { name: "Tanzania", provinces: ["Njombe", "Geita", "Simiyu", "Katavi", "Tanga", "Mara", "Kilimanjaro", "Manyara", "Arusha", "Singida", "Ruvuma", "Mtwara", "Lindi", "Iringa", "Dodoma", "Mjini Magharibi", "Unguja North", "Pwani", "Pemba South", "Pemba North", "Morogoro", "Dar Es Salaam", "Kigoma", "Kagera", "Tabora", "Shinyanga", "Mwanza", "Unguja South", "Rukwa", "Mbeya"], cities: ["Zanzibar", "Arusha", "Dar es Salaam"], map: "tanzania" },
    { name: "Thailand", provinces: ["Bangkok", "Samut Prakan", "Nonthaburi", "Pathum Thani", "Phra Nakhon Si Ayutthaya", "Ang Thong", "Lop Buri", "Sing Buri", "Chai Nat", "Saraburi", "Chon Buri", "Rayong", "Chanthaburi", "Trat", "Chachoengsao", "Prachin Buri", "Nakhon Nayok", "Sa Kaeo", "Nakhon Ratchasima", "Buriram", "Surin", "Si Sa Ket", "Ubon Ratchathani", "Yasothon", "Chaiyaphum", "Amnat Charoen", "Bueng Kan", "Nong Bua Lam Phu", "Khon Kaen", "Udon Thani", "Loei", "Nong Khai", "Maha Sarakham", "Roi Et", "Kalasin", "Sakon Nakhon", "Nakhon Phanom", "Mukdahan", "Chiang Mai", "Lamphun", "Lampang", "Uttaradit", "Phrae", "Nan", "Phayao", "Chiang Rai", "Mae Hong Son", "Nakhon Sawan", "Uthai Thani", "Kamphaeng Phet", "Tak", "Sukhothai", "Phitsanulok", "Phichit", "Phetchabun", "Ratchaburi", "Kanchanaburi", "Suphan Buri", "Nakhon Pathom", "Samut Sakhon", "Samut Songkhram", "Phetchaburi", "Prachuap Khiri Khan", "Nakhon Si Thammarat", "Krabi", "Phangnga", "Phuket", "Surat Thani", "Ranong", "Chumphon", "Songkhla", "Satun", "Trang", "Phatthalung", "Pattani", "Yala", "Narathiwat", "Lake Songkha"], cities: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Krabi", "Ayutthaya"], map: "thailand" },
    { name: "Timor-Leste", provinces: [] },
    { name: "Togo", provinces: [] },
    { name: "Tonga", provinces: [] },
    { name: "Trinidad and Tobago", provinces: [] },
    { name: "Tunisia", provinces: ["Ariana", "Beja", "Ben Arous", "Bizerte", "Gabès", "Gafsa", "Jendouba", "Kairouan", "Kasserine", "Kebili", "Kef", "Mahdia", "Manouba", "Mednine", "Monastir", "Nabeul 1", "Nabeul 2", "Sfax 1", "Sfax 2", "Sidi Bouzid", "Sousse", "Siliana", "Tataouine", "Tozeur", "Tunis 1", "Tunis 2", "Zaghouan"], cities: ["Tunis", "Sidi Bou Said", "Djerba"], map: "tunisia" },
    { name: "Turkey", provinces: [], cities: ["Istanbul", "Ankara", "Izmir", "Antalya", "Cappadocia (Nevşehir)", "Bodrum", "Pamukkale (Denizli)"] },
    { name: "Turkmenistan", provinces: [] },
    { name: "Tuvalu", provinces: [] },
    { name: "Uganda", provinces: [] },
    { name: "Ukraine", provinces: ["Cherkasy", "Chernihiv", "Chernivtsi", "Crimea", "Dnipropetrovsk", "Donetsk", "Ivano-Frankivsk", "Kharkiv", "Kherson", "Khmelnytskyi", "Kirovohrad", "Kyiv", "Kyiv City", "Luhansk", "Lviv", "Mykolaiv", "Odessa", "Poltava", "Rivne", "Sumy", "Ternopil", "Vinnytsia", "Volyn", "Zakarpattia", "Zaporizhia", "Zhytomyr"], cities: ["Kyiv", "Lviv", "Odesa"], map: "ukraine" },
    { name: "United Arab Emirates", provinces: ["Abu Dhabi", "Ajman", "Dubai", "Fujairah", "Ras al-Khaimah", "Sharjah", "Umm al-Quwain"], cities: ["Dubai", "Abu Dhabi", "Sharjah"], map: "uae" },
    { name: "United Kingdom", provinces: ["England", "Scotland", "Wales", "Northern Ireland"], cities: ["London", "Edinburgh", "Manchester", "Liverpool", "Glasgow", "Cardiff", "Belfast", "Oxford", "Bath", "York"] },
    { name: "United States", provinces: ["Alaska", "Alabama", "Arkansas", "Arizona", "California", "Colorado", "Connecticut", "Washington, DC", "Delaware", "Florida", "Georgia", "Hawaii", "Iowa", "Idaho", "Illinois", "Indiana", "Kansas", "Kentucky", "Louisiana", "Massachusetts", "Maryland", "Maine", "Michigan", "Minnesota", "Missouri", "Mississippi", "Montana", "North Carolina", "North Dakota", "Nebraska", "New Hampshire", "New Jersey", "New Mexico", "Nevada", "New York", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Virginia", "Vermont", "Washington", "Wisconsin", "West Virginia", "Wyoming"], cities: ["New York City", "Los Angeles", "Chicago", "San Francisco", "Las Vegas", "Miami", "Seattle", "Boston", "Washington D.C.", "New Orleans"], map: "usa" },
    { name: "Uruguay", provinces: [], cities: ["Montevideo", "Punta del Este", "Colonia del Sacramento"] },
    { name: "Uzbekistan", provinces: ["Andijan", "Bukhara", "Fergana", "Jizzakh", "Namangan", "Navoiy", "Qashqadaryo", "Karakalpakstan", "Samarqand", "Sirdaryo", "Surxondaryo", "Tashkent", "Tashkent", "Xorazm", "Aral Sea"], cities: ["Tashkent", "Samarkand", "Bukhara"], map: "uzbekistan" },
    { name: "Vanuatu", provinces: [] },
    { name: "Vatican City", provinces: [], cities: ["Vatican City"] },
    { name: "Venezuela", provinces: [] },
    { name: "Vietnam", provinces: ["An Giang", "Ba Ria–Vung Tau", "Bac Lieu", "Bac Giang", "Bac Kan", "Bac Ninh", "Ben Tre", "Binh Duong", "Binh Dinh", "Binh Phuoc", "Binh Thuan", "Ca Mau", "Cao Bang", "Can Tho", "Da Nang", "Dak Lak", "Dak Nong", "Dong Nai", "Dong Thap", "Dien Bien", "Gia Lai", "Ha Giang", "Ha Nam", "Ha Noi", "Ha Tinh", "Hai Duong", "Hai Phong", "Hau Giang", "Hoa Binh", "Ho Chi Minh", "Hoang Sa", "Hung Yen", "Khanh Hoa", "Kien Giang", "Kon Tum", "Lam Dong", "Lang Son", "Lai Chau", "Lao Cai", "Long An", "Nam Dinh", "Ninh Binh", "Ninh Thuan", "Nghe An", "Phu Tho", "Phu Yen", "Quang Binh", "Quang Nam", "Quang Ngai", "Quang Ninh", "Quang Tri", "Son La", "Soc Trang", "Tay Ninh", "Thanh Hoa", "Thai Binh", "Thai Nguyen", "Thua Thien-Hue", "Tien Giang", "Tra Vinh", "Truong Sa", "Tuyen Quang", "Vinh Long", "Vinh Phuc", "Yen Bai"], cities: ["Hanoi", "Ho Chi Minh City", "Da Nang", "Hai Phong", "Ha Long Bay (Quang Ninh)", "Nha Trang (Khanh Hoa)", "Da Lat (Lam Dong)", "Hue", "Hoi An (Quang Nam)", "Ninh Binh", "Sapa (Lao Cai)"], map: "vietnam" },
    { name: "Yemen", provinces: [] },
    { name: "Zambia", provinces: [] },
    { name: "Zimbabwe", provinces: ["Matebeleland North", "Mashonaland Central", "Manicaland", "Midlands", "Masvingo", "Bulawayo", "Matebeleland South", "Mashonaland West", "Mashonaland East", "Harare"], map: "zimbabwe" },
  ]
};
