/* ===========================================================
   Reference geography data for the "browse list" curtain menu.

   - `countries` is a near-complete list of the world's countries,
     so the country curtain always has something to pick from.
   - `provinces` is filled in for Italy as a worked example.
     Every other country starts with an empty list — add to it
     whenever you want a country's regions to show up in the
     curtain instead of needing to be typed by hand.

   This file only feeds the curtain menu. You can always type a
   custom name instead, for anything missing here.
   =========================================================== */

const GEO_DATA = {
  countries: [
    { name: "Afghanistan", provinces: [] },
    { name: "Albania", provinces: [] },
    { name: "Algeria", provinces: [] },
    { name: "Andorra", provinces: [] },
    { name: "Angola", provinces: [] },
    { name: "Antigua and Barbuda", provinces: [] },
    { name: "Argentina", provinces: [] },
    { name: "Armenia", provinces: [] },
    { name: "Australia", provinces: [] },
    { name: "Austria", provinces: [] },
    { name: "Azerbaijan", provinces: [] },
    { name: "Bahamas", provinces: [] },
    { name: "Bahrain", provinces: [] },
    { name: "Bangladesh", provinces: [] },
    { name: "Barbados", provinces: [] },
    { name: "Belarus", provinces: [] },
    { name: "Belgium", provinces: [] },
    { name: "Belize", provinces: [] },
    { name: "Benin", provinces: [] },
    { name: "Bhutan", provinces: [] },
    { name: "Bolivia", provinces: [] },
    { name: "Bosnia and Herzegovina", provinces: [] },
    { name: "Botswana", provinces: [] },
    { name: "Brazil", provinces: [] },
    { name: "Brunei", provinces: [] },
    { name: "Bulgaria", provinces: [] },
    { name: "Burkina Faso", provinces: [] },
    { name: "Burundi", provinces: [] },
    { name: "Cabo Verde", provinces: [] },
    { name: "Cambodia", provinces: [] },
    { name: "Cameroon", provinces: [] },
    { name: "Canada", provinces: [] },
    { name: "Central African Republic", provinces: [] },
    { name: "Chad", provinces: [] },
    { name: "Chile", provinces: [] },
    { name: "China", provinces: [] },
    { name: "Colombia", provinces: [] },
    { name: "Comoros", provinces: [] },
    { name: "Congo (Republic of the)", provinces: [] },
    { name: "Congo (Democratic Republic of the)", provinces: [] },
    { name: "Costa Rica", provinces: [] },
    { name: "Croatia", provinces: [] },
    { name: "Cuba", provinces: [] },
    { name: "Cyprus", provinces: [] },
    { name: "Czechia", provinces: [] },
    { name: "Denmark", provinces: [] },
    { name: "Djibouti", provinces: [] },
    { name: "Dominica", provinces: [] },
    { name: "Dominican Republic", provinces: [] },
    { name: "Ecuador", provinces: [] },
    { name: "Egypt", provinces: [] },
    { name: "El Salvador", provinces: [] },
    { name: "Equatorial Guinea", provinces: [] },
    { name: "Eritrea", provinces: [] },
    { name: "Estonia", provinces: [] },
    { name: "Eswatini", provinces: [] },
    { name: "Ethiopia", provinces: [] },
    { name: "Fiji", provinces: [] },
    { name: "Finland", provinces: [] },
    { name: "France", provinces: [] },
    { name: "Gabon", provinces: [] },
    { name: "Gambia", provinces: [] },
    { name: "Georgia", provinces: [] },
    { name: "Germany", provinces: [] },
    { name: "Ghana", provinces: [] },
    { name: "Greece", provinces: [] },
    { name: "Grenada", provinces: [] },
    { name: "Guatemala", provinces: [] },
    { name: "Guinea", provinces: [] },
    { name: "Guinea-Bissau", provinces: [] },
    { name: "Guyana", provinces: [] },
    { name: "Haiti", provinces: [] },
    { name: "Honduras", provinces: [] },
    { name: "Hungary", provinces: [] },
    { name: "Iceland", provinces: [] },
    { name: "India", provinces: [] },
    { name: "Indonesia", provinces: [] },
    { name: "Iran", provinces: [] },
    { name: "Iraq", provinces: [] },
    { name: "Ireland", provinces: [] },
    { name: "Israel", provinces: [] },
    {
      name: "Italy",
      provinces: [
        "Torino", "Alessandria", "Asti", "Biella", "Cuneo", "Novara", "Verbano-Cusio-Ossola", "Vercelli",
        "Aosta",
        "Genova", "Imperia", "La Spezia", "Savona",
        "Milano", "Bergamo", "Brescia", "Como", "Cremona", "Lecco", "Lodi", "Mantova", "Monza e della Brianza", "Pavia", "Sondrio", "Varese",
        "Trento", "Bolzano",
        "Venezia", "Belluno", "Padova", "Rovigo", "Treviso", "Verona", "Vicenza",
        "Udine", "Gorizia", "Pordenone", "Trieste",
        "Bologna", "Ferrara", "Forlì-Cesena", "Modena", "Parma", "Piacenza", "Ravenna", "Reggio Emilia", "Rimini",
        "Firenze", "Arezzo", "Grosseto", "Livorno", "Lucca", "Massa-Carrara", "Pisa", "Pistoia", "Prato", "Siena",
        "Perugia", "Terni",
        "Ancona", "Ascoli Piceno", "Fermo", "Macerata", "Pesaro e Urbino",
        "Roma Capitale", "Frosinone", "Latina", "Rieti", "Viterbo",
        "L'Aquila", "Chieti", "Pescara", "Teramo",
        "Campobasso", "Isernia",
        "Napoli", "Avellino", "Benevento", "Caserta", "Salerno",
        "Bari", "Barletta-Andria-Trani", "Brindisi", "Foggia", "Lecce", "Taranto",
        "Matera", "Potenza",
        "Reggio Calabria", "Catanzaro", "Cosenza", "Crotone", "Vibo Valentia",
        "Palermo", "Catania", "Messina", "Agrigento", "Caltanissetta", "Enna", "Ragusa", "Siracusa", "Trapani",
        "Cagliari", "Sassari", "Nuoro", "Oristano", "Sud Sardegna"
      ]
    },
    { name: "Ivory Coast", provinces: [] },
    { name: "Jamaica", provinces: [] },
    { name: "Japan", provinces: [] },
    { name: "Jordan", provinces: [] },
    { name: "Kazakhstan", provinces: [] },
    { name: "Kenya", provinces: [] },
    { name: "Kiribati", provinces: [] },
    { name: "Kosovo", provinces: [] },
    { name: "Kuwait", provinces: [] },
    { name: "Kyrgyzstan", provinces: [] },
    { name: "Laos", provinces: [] },
    { name: "Latvia", provinces: [] },
    { name: "Lebanon", provinces: [] },
    { name: "Lesotho", provinces: [] },
    { name: "Liberia", provinces: [] },
    { name: "Libya", provinces: [] },
    { name: "Liechtenstein", provinces: [] },
    { name: "Lithuania", provinces: [] },
    { name: "Luxembourg", provinces: [] },
    { name: "Madagascar", provinces: [] },
    { name: "Malawi", provinces: [] },
    { name: "Malaysia", provinces: [] },
    { name: "Maldives", provinces: [] },
    { name: "Mali", provinces: [] },
    { name: "Malta", provinces: [] },
    { name: "Marshall Islands", provinces: [] },
    { name: "Mauritania", provinces: [] },
    { name: "Mauritius", provinces: [] },
    { name: "Mexico", provinces: [] },
    { name: "Micronesia", provinces: [] },
    { name: "Moldova", provinces: [] },
    { name: "Monaco", provinces: [] },
    { name: "Mongolia", provinces: [] },
    { name: "Montenegro", provinces: [] },
    { name: "Morocco", provinces: [] },
    { name: "Mozambique", provinces: [] },
    { name: "Myanmar", provinces: [] },
    { name: "Namibia", provinces: [] },
    { name: "Nauru", provinces: [] },
    { name: "Nepal", provinces: [] },
    { name: "Netherlands", provinces: [] },
    { name: "New Zealand", provinces: [] },
    { name: "Nicaragua", provinces: [] },
    { name: "Niger", provinces: [] },
    { name: "Nigeria", provinces: [] },
    { name: "North Korea", provinces: [] },
    { name: "North Macedonia", provinces: [] },
    { name: "Norway", provinces: [] },
    { name: "Oman", provinces: [] },
    { name: "Pakistan", provinces: [] },
    { name: "Palau", provinces: [] },
    { name: "Palestine", provinces: [] },
    { name: "Panama", provinces: [] },
    { name: "Papua New Guinea", provinces: [] },
    { name: "Paraguay", provinces: [] },
    { name: "Peru", provinces: [] },
    { name: "Philippines", provinces: [] },
    { name: "Poland", provinces: [] },
    { name: "Portugal", provinces: [] },
    { name: "Qatar", provinces: [] },
    { name: "Romania", provinces: [] },
    { name: "Russia", provinces: [] },
    { name: "Rwanda", provinces: [] },
    { name: "Saint Kitts and Nevis", provinces: [] },
    { name: "Saint Lucia", provinces: [] },
    { name: "Saint Vincent and the Grenadines", provinces: [] },
    { name: "Samoa", provinces: [] },
    { name: "San Marino", provinces: [] },
    { name: "Sao Tome and Principe", provinces: [] },
    { name: "Saudi Arabia", provinces: [] },
    { name: "Senegal", provinces: [] },
    { name: "Serbia", provinces: [] },
    { name: "Seychelles", provinces: [] },
    { name: "Sierra Leone", provinces: [] },
    { name: "Singapore", provinces: [] },
    { name: "Slovakia", provinces: [] },
    { name: "Slovenia", provinces: [] },
    { name: "Solomon Islands", provinces: [] },
    { name: "Somalia", provinces: [] },
    { name: "South Africa", provinces: [] },
    { name: "South Korea", provinces: [] },
    { name: "South Sudan", provinces: [] },
    { name: "Spain", provinces: [] },
    { name: "Sri Lanka", provinces: [] },
    { name: "Sudan", provinces: [] },
    { name: "Suriname", provinces: [] },
    { name: "Sweden", provinces: [] },
    { name: "Switzerland", provinces: [] },
    { name: "Syria", provinces: [] },
    { name: "Taiwan", provinces: [] },
    { name: "Tajikistan", provinces: [] },
    { name: "Tanzania", provinces: [] },
    { name: "Thailand", provinces: [] },
    { name: "Timor-Leste", provinces: [] },
    { name: "Togo", provinces: [] },
    { name: "Tonga", provinces: [] },
    { name: "Trinidad and Tobago", provinces: [] },
    { name: "Tunisia", provinces: [] },
    { name: "Turkey", provinces: [] },
    { name: "Turkmenistan", provinces: [] },
    { name: "Tuvalu", provinces: [] },
    { name: "Uganda", provinces: [] },
    { name: "Ukraine", provinces: [] },
    { name: "United Arab Emirates", provinces: [] },
    { name: "United Kingdom", provinces: [] },
    { name: "United States", provinces: [] },
    { name: "Uruguay", provinces: [] },
    { name: "Uzbekistan", provinces: [] },
    { name: "Vanuatu", provinces: [] },
    { name: "Vatican City", provinces: [] },
    { name: "Venezuela", provinces: [] },
    { name: "Vietnam", provinces: [] },
    { name: "Yemen", provinces: [] },
    { name: "Zambia", provinces: [] },
    { name: "Zimbabwe", provinces: [] }
  ]
};
